### PR TITLE
Issue #101: Non-owner Cannot Save Profile Bug

### LINKED ISSUE #101: Non-owners Cannot Save Profile
Non-owners always get the following error when saving their profile. This occurs when isOwner is false and not changed.

```json
{"type":"io.github.groupease.channelmember.ChannelMemberNotOwnerException","message":"Member must be owner to update isOwner"}
```

### PR DESCRIPTION
**Pull request by mckoon**
* Fixes bugs with member saving validation.

Closes #101

### CODE REVIEW

File: groupease-server/src/main/java/io/github/groupease/channelmember/DefaultChannelMemberService.java [hunk 1]
```diff
@@ -126,27 +126,28 @@ public Member update(
...
          * Ensure if "isOwner" is being changed, that current user is a channel admin.
+         * Also ensure non-owners can only edit their own profile.
          */
 
         Member editor = getForCurrentUser(toUpdate.getChannel().getId());
-        Member existingMember = getByMemberId(toUpdate.getId());
-
-        if(editor.isOwner() || editor.getId().equals(toUpdate.getId())){   //Is the current user an owner? or editing themself?
-            if(toUpdate.isOwner() == existingMember.isOwner()){ //Changing isOwner?
-                if(editor.isOwner()){
```
Comment (mckoon) [inline groupease-server/src/main/java/io/github/groupease/channelmember/DefaultChannelMemberService.java]: This line (and the one above) added in Issue #70 caused a bug that prohibited any non-user from editing their profile.  It always would throw `ChannelMemberNotOwnerException` on line 142 below.
